### ISSUE TITLE
Again this forge issue

### ISSUE THREAD

**Issue by TheNickSkater** [PaperMC/Travertine#97]
So well, you did already had many posts about this issue. But I WANT THIS TO GET FIXES, PLEAAASE.

What I mean? When an 1.8 Forge Client connects to my 1.7/1.8 protocol hack server, all 1.7 clients get kicked...
Why? Cause forge send Packets which the server/1.7client can't handle.. Disabling forge support in config does not help either.. Isn't it possible to stop forge packets from sending to players when forge support is turned off? Thats all it would take to stopp it..

Why I know? Some Hack clients have an option to hide forge, that means it stops sending forge packets to the server.. And all of a sudden.. it works.

If possible, please please do fix this, it would not only help me..

**Comment by electronicboy** [comment]
This is not a waterfall issue, nor is their anything we can do about the client sending invalid data for the version of mc you're running when using hacks to allow them to connect.

**Comment by TheNickSkater** [comment]
Then I would like to know, why this is not happening on the default BungeeCord 1.7/1.8 version.
Cause I dont see a problem there.

**Comment by electronicboy** [comment]
Since the 1.7/1.8 versions of bungee, there have been several hundred commits to the project, I couldn't say why it would work there and not here

But, ultimately, protocol hacks are unsupported, we have no interest in trying to diagnose and deal with issues, especially when they're not being triggered on our software, both individual versions work

If somebody wants to spend the time to investigate the issue or submit a PR, we'll be more than happy to look over it, but this isn't something we're willing to invest our time in
